server:
  port: 8082
spring:
  datasource:
    password: Abh1$h3k
    url: jdbc:mysql://${DB_HOST:localhost}:3306/orderdb
    username: root
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ORDER-SERVICE
  config:
    import: configserver:http://localhost:9296


resilience4j:
  circuitbreaker:
    instances:
      external:
        slidingWindowSize: 10
        eventConsumerBufferSize: 10
        failureRateThreshold: 50
        minimumNumberOfCalls: 5
        automaticTransitionFromOpenToHalfOpenEnabled: true
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowType: COUNT_BASED
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: ${EUREKA_SERVER_ADDRESS:http://localhost:8761/eureka}
