#api version
#Kind resources
#specification for resource
  #diff based on diff resources
#status information

apiVersion: apps/v1
kind: Deployment
metadata:
  name: service-registry
spec:
  selector:
    matchLabels:
      app: service-registry
  template:
    metadata:
      labels:
        app: service-registry
    spec: 
      containers:
        - name: service-registry
          image : abhishekkumar627/service-registry:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8761